# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'

target 'RTCSolution' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for RTCSolution
#begin 
  
  pod 'RTCInteractiveLiveClass', :path => './RTCInteractiveLiveClass'
   
  pod 'RTCCommon', :path => './RTCCommon'
  
  pod 'RTCCommonView', :path => './RTCCommonView'
  
#end

 pod 'AliRTCSdk',        :path => 'AliRtcSDK_iOS' 
 pod 'AFNetworking',  '4.0.1' 

 
end
